import Head from 'next/head'
import { Inter } from '@next/font/google'
import Header from '@/components/Header'
import Hero from '@/components/Hero'
import About from '@/components/About'
import WorkExperience from '@/components/WorkExperience'
import Skills from '@/components/Skills'
import Projects from '@/components/Projects'
import ContactMe from '@/components/ContactMe'
import Link from 'next/link'
import { GetStaticProps } from 'next'
import { PageInfo, Experience, Project, Skill, Social } from 'typing'
import { fetchPageInfo } from '@/utils/fetchPageInfo'
import { fetchExperiences } from '@/utils/fetchExperiences'
import { fetchProjects } from '@/utils/fetchProjects'
import { fetchSkills } from '@/utils/fetchSkills'
import { fetchSocial } from '@/utils/fetchSocials'
import { urlFor } from 'sanity'

const inter = Inter({ subsets: ['latin'] })

type Props = {
  pageInfo: PageInfo
  experiences: Experience[]
  projects: Project[]
  skills: Skill[]
  // socials: Social[]
}

const Home = ({
  pageInfo = {
    name: '',
    _type: 'pageInfo',
    address: '',
    backgroundInformation: '',
    email: '',
    role: '',
    heroImage: undefined,
    phoneNumber: '',
    profilePic: '',
    _createdAt: '',
    _id: '',
    _rev: '',
    _updatedAt: ''
  },
  experiences = [],
  projects = [],
  skills = [],
  // socials,
}: Props) => {
  return (
    <div className='bg-[rgb(36,36,36)] text-white h-screen snap-y snap-mandatory overflow-x-hidden overflow-y-scroll z-0 scrollbar-thin scrollbar-track-gray-400/20 scrollbar-thumb-[#f7ab0a]/80 scroll-smooth'>
      <Head>
        <title>{pageInfo?.name} - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={urlFor(pageInfo?.heroImage).url()} />
      </Head>

      {/* header */}
      <Header
        // socials
      />

      {/* hero */}
      <section id='hero' className='snap-start'>
        <Hero pageInfo={pageInfo} />
      </section>

      {/* about */}
      <section id='about' className='snap-center'>
        <About pageInfo={pageInfo} />
      </section>

      {/* experience */}
      <section id='experience' className='snap-center'>
        <WorkExperience experiences={experiences} />
      </section>

      {/* skills */}
      <section id='skills' className='snap-start'>
        <Skills skills={skills} />
      </section>

      {/* projects */}
      <section id='projects' className='snap-start'>
        <Projects projects={projects} />
      </section>


      {/* contact me */}
      <section id='contact' className='snap-start'>
        <ContactMe />
      </section>

      <Link href="#hero">
        <footer className='sticky bottom-5 w-full cursor-pointer'>
          <div className='flex items-center justify-center'>
            <img
              className='h-10 w-10 rounded-full filter grayscale hover:grayscale-0'
              src="IMG_1220.jpg"
              alt="IMG_1220.jpg"
            />
          </div>
        </footer>
      </Link>
    </div>
  )
}
export default Home;

export const getStaticProps
  // : GetStaticProps<Props>
  = async () => {
  // const pageInfo: PageInfo = await fetchPageInfo();
  // const experiences: Experience[] = await fetchExperiences();
  // const projects: Project[] = await fetchProjects();
  // const skills: Skill[] = await fetchSkills();
  // const socials: Social[] = await fetchSocial();
  // console.log('🚀 > socials', socials);

  return {
    props: {
      // pageInfo,
      // experiences,
      // projects,
      // skills,
      // socials,
    },
    revalidate: 10,
  }
}
